### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by JTD420** [yubie-re/gtav-sigscan#1]
Sorry for noob question but how do I compile this to run?

I've tried running cmake but I get an error about missing files such as `gtav-sigscan-main/gtav-sigscan-main/src/vendor/AES/src/AES.cpp`...

I'm guessing I am doing this the wrong way! Could someone point me in the right direction? Thanks in advance for any help!

**Comment by yubie-re** [comment]
`git submodule update --init --recursive` will download all the dependencies needed.

**Comment by JTD420** [comment]
Yes that was it thanks! 👍  
Sorry I only just noticed your reply - was about to go and comment with the fix myself and close this but you beat me too it haha :)
